default['xdebug']['cli_color'] = 1
default['xdebug']['scream'] = 0
default['xdebug']['remote_enable'] = "On"
default['xdebug']['remote_host'] = "localhost"
default['xdebug']['remote_port'] = 9000
default['xdebug']['remote_autostart'] = 0
default['xdebug']['remote_mode'] = "req"
default['xdebug']['remote_connect_back'] = 1
default['xdebug']['idekey'] = "macgdbp"
default['xdebug']['file_link_format'] = "txmt://open?url=file://%f&line=%1"
default['xdebug']['profiler_enable_trigger'] = 0
default['xdebug']['profiler_enable'] = 0
default['xdebug']['profiler_output_dir'] = "/tmp/cachegrind"
default['xdebug']['remote_cookie_expire_time'] = 36000
